module.exports = {
    products: [
        {
            _id: '1',
            name: 'Shirt 1',
            category: 'Shirts',
            image: '/images/product-1.jpg',
            price: 70,
            brand: 'Hiskywin',
            rating: 4.5,
            numReiews: 10,
            countInStock: 6,
        },
        {
            _id: '2',
            name: 'Shirt 2',
            category: 'Shirts',
            image: '/images/product-2.jpg',
            price: 60,
            brand: 'Nike',
            rating: 5,
            numReiews: 11,
            countInStock: 3,
        },
        {
            _id: '3',
            name: 'Shirt 3',
            category: 'Shirts',
            image: '/images/product-3.jpg',
            price: 70,
            brand: 'Hiskywin',
            rating: 4.5,
            numReiews: 10,
            countInStock: 6,
        },
        {
            _id: '4',
            name: 'Shirt 4',
            category: 'Shirts',
            image: '/images/product-4.jpg',
            price: 70,
            brand: 'Hiskywin',
            rating: 4.5,
            numReiews: 10,
            countInStock: 6,
        },
        {
            _id: '5',
            name: 'Shirt 5',
            category: 'Shirts',
            image: '/images/product-5.jpg',
            price: 70,
            brand: 'Hiskywin',
            rating: 4.5,
            numReiews: 10,
            countInStock: 6,
        },
        {
            _id: '6',
            name: 'Shirt 6',
            category: 'Shirts',
            image: '/images/product-6.jpg',
            price: 70,
            brand: 'Hiskywin',
            rating: 4.5,
            numReiews: 10,
            countInStock: 6,
        },
    ],
};